#!/usr/bin/env bash
# Render the agent source into ConfigMaps for the dev/validation rollout.
#
# Why not just ship an image: the cluster is reachable only through a slow
# tunnel, a 49MB image tar would not transfer, and there is no internal
# registry to push to. But python:3.12-slim is ALREADY present on the nodes,
# and the agent has zero third-party dependencies - so 52KB of source in a
# ConfigMap is the entire payload.
#
# This is a validation-rollout mechanism, not the production one. Before the
# agent goes on 0029/0043, build the image (see Dockerfile) and push it to a
# registry the nodes can pull from; ConfigMap-mounted source has no
# provenance, no immutable digest, and no way to roll back to a known build.
#
# ConfigMap keys cannot contain "/", so the package and its signals
# subpackage become two ConfigMaps mounted at parent and child paths.
set -euo pipefail

cd "$(dirname "$0")/.."
out=deploy/dev/agent-source-configmap.yaml

emit_cm() {
  local name=$1 dir=$2
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: ${name}"
  echo "  namespace: gpu-node-health"
  echo "data:"
  for f in "${dir}"/*.py; do
    echo "  $(basename "$f"): |"
    sed 's/^/    /' "$f"
  done
}

{
  echo "# GENERATED by deploy/render-dev-configmap.sh - do not edit by hand."
  emit_cm gpu-health-agent-src agent/gpu_health_agent
  echo "---"
  emit_cm gpu-health-agent-src-signals agent/gpu_health_agent/signals
} > "${out}"

echo "wrote ${out} ($(wc -c < "${out}") bytes)"
